const weatherMock = {
  "latitude": 51.5074,
  "longitude": 0.1278,
  "timezone": "Europe/London",
  "currently": {
      "time": 1573590598,
      "summary": "Partly Cloudy",
      "icon": "partly-cloudy-night",
      "nearestStormDistance": 48,
      "nearestStormBearing": 177,
      "precipIntensity": 0,
      "precipProbability": 0,
      "temperature": 7.62,
      "apparentTemperature": 4.83,
      "dewPoint": 5.71,
      "humidity": 0.88,
      "pressure": 999.3,
      "windSpeed": 4.5,
      "windGust": 10.6,
      "windBearing": 292,
      "cloudCover": 0.59,
      "uvIndex": 0,
      "visibility": 10.017,
      "ozone": 350.2
  },
  "minutely": {
      "summary": "Partly cloudy for the hour.",
      "icon": "partly-cloudy-night",
      "data": [
          {
              "time": 1573590540,
              "precipIntensity": 0,
              "precipProbability": 0
          },
          {
              "time": 1573590600,
              "precipIntensity": 0,
              "precipProbability": 0
          },
          {
              "time": 1573590660,
              "precipIntensity": 0,
              "precipProbability": 0
          },
          {
              "time": 1573590720,
              "precipIntensity": 0,
              "precipProbability": 0
          },
          {
              "time": 1573590780,
              "precipIntensity": 0,
              "precipProbability": 0
          },
          {
              "time": 1573590840,
              "precipIntensity": 0,
              "precipProbability": 0
          },
          {
              "time": 1573590900,
              "precipIntensity": 0,
              "precipProbability": 0
          },
          {
              "time": 1573590960,
              "precipIntensity": 0,
              "precipProbability": 0
          },
          {
              "time": 1573591020,
              "precipIntensity": 0,
              "precipProbability": 0
          },
          {
              "time": 1573591080,
              "precipIntensity": 0,
              "precipProbability": 0
          },
          {
              "time": 1573591140,
              "precipIntensity": 0,
              "precipProbability": 0
          },
          {
              "time": 1573591200,
              "precipIntensity": 0,
              "precipProbability": 0
          },
          {
              "time": 1573591260,
              "precipIntensity": 0,
              "precipProbability": 0
          },
          {
              "time": 1573591320,
              "precipIntensity": 0,
              "precipProbability": 0
          },
          {
              "time": 1573591380,
              "precipIntensity": 0,
              "precipProbability": 0
          },
          {
              "time": 1573591440,
              "precipIntensity": 0,
              "precipProbability": 0
          },
          {
              "time": 1573591500,
              "precipIntensity": 0,
              "precipProbability": 0
          },
          {
              "time": 1573591560,
              "precipIntensity": 0,
              "precipProbability": 0
          },
          {
              "time": 1573591620,
              "precipIntensity": 0,
              "precipProbability": 0
          },
          {
              "time": 1573591680,
              "precipIntensity": 0,
              "precipProbability": 0
          },
          {
              "time": 1573591740,
              "precipIntensity": 0,
              "precipProbability": 0
          },
          {
              "time": 1573591800,
              "precipIntensity": 0,
              "precipProbability": 0
          },
          {
              "time": 1573591860,
              "precipIntensity": 0,
              "precipProbability": 0
          },
          {
              "time": 1573591920,
              "precipIntensity": 0,
              "precipProbability": 0
          },
          {
              "time": 1573591980,
              "precipIntensity": 0,
              "precipProbability": 0
          },
          {
              "time": 1573592040,
              "precipIntensity": 0,
              "precipProbability": 0
          },
          {
              "time": 1573592100,
              "precipIntensity": 0,
              "precipProbability": 0
          },
          {
              "time": 1573592160,
              "precipIntensity": 0,
              "precipProbability": 0
          },
          {
              "time": 1573592220,
              "precipIntensity": 0,
              "precipProbability": 0
          },
          {
              "time": 1573592280,
              "precipIntensity": 0,
              "precipProbability": 0
          },
          {
              "time": 1573592340,
              "precipIntensity": 0,
              "precipProbability": 0
          },
          {
              "time": 1573592400,
              "precipIntensity": 0,
              "precipProbability": 0
          },
          {
              "time": 1573592460,
              "precipIntensity": 0,
              "precipProbability": 0
          },
          {
              "time": 1573592520,
              "precipIntensity": 0,
              "precipProbability": 0
          },
          {
              "time": 1573592580,
              "precipIntensity": 0,
              "precipProbability": 0
          },
          {
              "time": 1573592640,
              "precipIntensity": 0,
              "precipProbability": 0
          },
          {
              "time": 1573592700,
              "precipIntensity": 0,
              "precipProbability": 0
          },
          {
              "time": 1573592760,
              "precipIntensity": 0,
              "precipProbability": 0
          },
          {
              "time": 1573592820,
              "precipIntensity": 0,
              "precipProbability": 0
          },
          {
              "time": 1573592880,
              "precipIntensity": 0,
              "precipProbability": 0
          },
          {
              "time": 1573592940,
              "precipIntensity": 0,
              "precipProbability": 0
          },
          {
              "time": 1573593000,
              "precipIntensity": 0,
              "precipProbability": 0
          },
          {
              "time": 1573593060,
              "precipIntensity": 0,
              "precipProbability": 0
          },
          {
              "time": 1573593120,
              "precipIntensity": 0,
              "precipProbability": 0
          },
          {
              "time": 1573593180,
              "precipIntensity": 0,
              "precipProbability": 0
          },
          {
              "time": 1573593240,
              "precipIntensity": 0,
              "precipProbability": 0
          },
          {
              "time": 1573593300,
              "precipIntensity": 0,
              "precipProbability": 0
          },
          {
              "time": 1573593360,
              "precipIntensity": 0,
              "precipProbability": 0
          },
          {
              "time": 1573593420,
              "precipIntensity": 0,
              "precipProbability": 0
          },
          {
              "time": 1573593480,
              "precipIntensity": 0,
              "precipProbability": 0
          },
          {
              "time": 1573593540,
              "precipIntensity": 0,
              "precipProbability": 0
          },
          {
              "time": 1573593600,
              "precipIntensity": 0,
              "precipProbability": 0
          },
          {
              "time": 1573593660,
              "precipIntensity": 0,
              "precipProbability": 0
          },
          {
              "time": 1573593720,
              "precipIntensity": 0,
              "precipProbability": 0
          },
          {
              "time": 1573593780,
              "precipIntensity": 0,
              "precipProbability": 0
          },
          {
              "time": 1573593840,
              "precipIntensity": 0,
              "precipProbability": 0
          },
          {
              "time": 1573593900,
              "precipIntensity": 0,
              "precipProbability": 0
          },
          {
              "time": 1573593960,
              "precipIntensity": 0,
              "precipProbability": 0
          },
          {
              "time": 1573594020,
              "precipIntensity": 0,
              "precipProbability": 0
          },
          {
              "time": 1573594080,
              "precipIntensity": 0,
              "precipProbability": 0
          },
          {
              "time": 1573594140,
              "precipIntensity": 0,
              "precipProbability": 0
          }
      ]
  },
  "hourly": {
      "summary": "Overcast throughout the day.",
      "icon": "cloudy",
      "data": [
          {
              "time": 1573588800,
              "summary": "Mostly Cloudy",
              "icon": "partly-cloudy-night",
              "precipIntensity": 0.0065,
              "precipProbability": 0.08,
              "precipType": "rain",
              "temperature": 7.77,
              "apparentTemperature": 4.99,
              "dewPoint": 5.76,
              "humidity": 0.87,
              "pressure": 999,
              "windSpeed": 4.54,
              "windGust": 10.51,
              "windBearing": 284,
              "cloudCover": 0.68,
              "uvIndex": 0,
              "visibility": 9.759,
              "ozone": 349.8
          },
          {
              "time": 1573592400,
              "summary": "Partly Cloudy",
              "icon": "partly-cloudy-night",
              "precipIntensity": 0.0001,
              "precipProbability": 0.07,
              "precipType": "rain",
              "temperature": 7.56,
              "apparentTemperature": 4.79,
              "dewPoint": 5.67,
              "humidity": 0.88,
              "pressure": 999.5,
              "windSpeed": 4.45,
              "windGust": 10.62,
              "windBearing": 298,
              "cloudCover": 0.5,
              "uvIndex": 0,
              "visibility": 11.253,
              "ozone": 350.3
          },
          {
              "time": 1573596000,
              "summary": "Partly Cloudy",
              "icon": "partly-cloudy-night",
              "precipIntensity": 0.0081,
              "precipProbability": 0.07,
              "precipType": "rain",
              "temperature": 7.94,
              "apparentTemperature": 5.28,
              "dewPoint": 5.74,
              "humidity": 0.86,
              "pressure": 999.9,
              "windSpeed": 4.4,
              "windGust": 10.38,
              "windBearing": 292,
              "cloudCover": 0.38,
              "uvIndex": 0,
              "visibility": 16.093,
              "ozone": 349.6
          },
          {
              "time": 1573599600,
              "summary": "Clear",
              "icon": "clear-night",
              "precipIntensity": 0.0141,
              "precipProbability": 0.08,
              "precipType": "rain",
              "temperature": 8.17,
              "apparentTemperature": 5.64,
              "dewPoint": 5.68,
              "humidity": 0.84,
              "pressure": 1000.2,
              "windSpeed": 4.25,
              "windGust": 9.97,
              "windBearing": 289,
              "cloudCover": 0.3,
              "uvIndex": 0,
              "visibility": 16.093,
              "ozone": 348.4
          },
          {
              "time": 1573603200,
              "summary": "Clear",
              "icon": "clear-night",
              "precipIntensity": 0.0182,
              "precipProbability": 0.08,
              "precipType": "rain",
              "temperature": 8.04,
              "apparentTemperature": 5.6,
              "dewPoint": 5.42,
              "humidity": 0.84,
              "pressure": 1000.6,
              "windSpeed": 3.98,
              "windGust": 9.45,
              "windBearing": 289,
              "cloudCover": 0.24,
              "uvIndex": 0,
              "visibility": 16.093,
              "ozone": 347.5
          },
          {
              "time": 1573606800,
              "summary": "Clear",
              "icon": "clear-night",
              "precipIntensity": 0.0124,
              "precipProbability": 0.07,
              "precipType": "rain",
              "temperature": 7.93,
              "apparentTemperature": 5.59,
              "dewPoint": 5.11,
              "humidity": 0.82,
              "pressure": 1000.7,
              "windSpeed": 3.76,
              "windGust": 8.8,
              "windBearing": 285,
              "cloudCover": 0.15,
              "uvIndex": 0,
              "visibility": 16.093,
              "ozone": 347.2
          },
          {
              "time": 1573610400,
              "summary": "Clear",
              "icon": "clear-night",
              "precipIntensity": 0.0055,
              "precipProbability": 0.07,
              "precipType": "rain",
              "temperature": 7.82,
              "apparentTemperature": 5.56,
              "dewPoint": 4.77,
              "humidity": 0.81,
              "pressure": 1000.8,
              "windSpeed": 3.54,
              "windGust": 8.06,
              "windBearing": 285,
              "cloudCover": 0.05,
              "uvIndex": 0,
              "visibility": 16.093,
              "ozone": 347.2
          },
          {
              "time": 1573614000,
              "summary": "Clear",
              "icon": "clear-night",
              "precipIntensity": 0,
              "precipProbability": 0,
              "temperature": 7.67,
              "apparentTemperature": 5.48,
              "dewPoint": 4.38,
              "humidity": 0.8,
              "pressure": 1001,
              "windSpeed": 3.37,
              "windGust": 7.42,
              "windBearing": 289,
              "cloudCover": 0,
              "uvIndex": 0,
              "visibility": 16.093,
              "ozone": 347.3
          },
          {
              "time": 1573617600,
              "summary": "Clear",
              "icon": "clear-night",
              "precipIntensity": 0.009,
              "precipProbability": 0.12,
              "precipType": "rain",
              "temperature": 7.43,
              "apparentTemperature": 5.25,
              "dewPoint": 3.96,
              "humidity": 0.79,
              "pressure": 1001.2,
              "windSpeed": 3.29,
              "windGust": 7.04,
              "windBearing": 323,
              "cloudCover": 0,
              "uvIndex": 0,
              "visibility": 16.093,
              "ozone": 347.6
          },
          {
              "time": 1573621200,
              "summary": "Clear",
              "icon": "clear-night",
              "precipIntensity": 0.0234,
              "precipProbability": 0.16,
              "precipType": "rain",
              "temperature": 7.22,
              "apparentTemperature": 5.02,
              "dewPoint": 3.67,
              "humidity": 0.78,
              "pressure": 1001.4,
              "windSpeed": 3.23,
              "windGust": 6.78,
              "windBearing": 224,
              "cloudCover": 0.03,
              "uvIndex": 0,
              "visibility": 16.093,
              "ozone": 348.1
          },
          {
              "time": 1573624800,
              "summary": "Clear",
              "icon": "clear-night",
              "precipIntensity": 0.032,
              "precipProbability": 0.19,
              "precipType": "rain",
              "temperature": 7.03,
              "apparentTemperature": 4.83,
              "dewPoint": 3.57,
              "humidity": 0.79,
              "pressure": 1001.6,
              "windSpeed": 3.17,
              "windGust": 6.45,
              "windBearing": 273,
              "cloudCover": 0.14,
              "uvIndex": 0,
              "visibility": 16.093,
              "ozone": 348.3
          },
          {
              "time": 1573628400,
              "summary": "Partly Cloudy",
              "icon": "partly-cloudy-night",
              "precipIntensity": 0.0178,
              "precipProbability": 0.16,
              "precipType": "rain",
              "temperature": 6.78,
              "apparentTemperature": 4.62,
              "dewPoint": 3.51,
              "humidity": 0.8,
              "pressure": 1001.8,
              "windSpeed": 3.04,
              "windGust": 5.9,
              "windBearing": 328,
              "cloudCover": 0.4,
              "uvIndex": 0,
              "visibility": 16.093,
              "ozone": 348.3
          },
          {
              "time": 1573632000,
              "summary": "Mostly Cloudy",
              "icon": "partly-cloudy-day",
              "precipIntensity": 0,
              "precipProbability": 0,
              "temperature": 6.49,
              "apparentTemperature": 4.4,
              "dewPoint": 3.63,
              "humidity": 0.82,
              "pressure": 1001.9,
              "windSpeed": 2.86,
              "windGust": 5.29,
              "windBearing": 223,
              "cloudCover": 0.73,
              "uvIndex": 0,
              "visibility": 16.093,
              "ozone": 348
          },
          {
              "time": 1573635600,
              "summary": "Overcast",
              "icon": "cloudy",
              "precipIntensity": 0,
              "precipProbability": 0,
              "temperature": 6.25,
              "apparentTemperature": 4.21,
              "dewPoint": 3.76,
              "humidity": 0.84,
              "pressure": 1001.6,
              "windSpeed": 2.72,
              "windGust": 4.82,
              "windBearing": 261,
              "cloudCover": 0.97,
              "uvIndex": 0,
              "visibility": 16.093,
              "ozone": 347.4
          },
          {
              "time": 1573639200,
              "summary": "Overcast",
              "icon": "cloudy",
              "precipIntensity": 0,
              "precipProbability": 0,
              "temperature": 6.55,
              "apparentTemperature": 4.57,
              "dewPoint": 4.01,
              "humidity": 0.84,
              "pressure": 1001.3,
              "windSpeed": 2.71,
              "windGust": 4.57,
              "windBearing": 260,
              "cloudCover": 1,
              "uvIndex": 0,
              "visibility": 16.093,
              "ozone": 346.1
          },
          {
              "time": 1573642800,
              "summary": "Overcast",
              "icon": "cloudy",
              "precipIntensity": 0,
              "precipProbability": 0,
              "temperature": 7.07,
              "apparentTemperature": 5.16,
              "dewPoint": 4.38,
              "humidity": 0.83,
              "pressure": 1000.8,
              "windSpeed": 2.77,
              "windGust": 4.48,
              "windBearing": 253,
              "cloudCover": 0.99,
              "uvIndex": 1,
              "visibility": 16.093,
              "ozone": 344.6
          },
          {
              "time": 1573646400,
              "summary": "Overcast",
              "icon": "cloudy",
              "precipIntensity": 0,
              "precipProbability": 0,
              "temperature": 7.78,
              "apparentTemperature": 5.95,
              "dewPoint": 4.59,
              "humidity": 0.8,
              "pressure": 1000.3,
              "windSpeed": 2.83,
              "windGust": 4.53,
              "windBearing": 239,
              "cloudCover": 0.98,
              "uvIndex": 1,
              "visibility": 16.093,
              "ozone": 343.9
          },
          {
              "time": 1573650000,
              "summary": "Overcast",
              "icon": "cloudy",
              "precipIntensity": 0.0051,
              "precipProbability": 0.06,
              "precipType": "rain",
              "temperature": 8.19,
              "apparentTemperature": 6.45,
              "dewPoint": 4.54,
              "humidity": 0.78,
              "pressure": 999.4,
              "windSpeed": 2.83,
              "windGust": 4.81,
              "windBearing": 231,
              "cloudCover": 0.99,
              "uvIndex": 1,
              "visibility": 16.093,
              "ozone": 344.1
          },
          {
              "time": 1573653600,
              "summary": "Overcast",
              "icon": "cloudy",
              "precipIntensity": 0.0139,
              "precipProbability": 0.05,
              "precipType": "rain",
              "temperature": 8.42,
              "apparentTemperature": 6.74,
              "dewPoint": 4.15,
              "humidity": 0.75,
              "pressure": 998.5,
              "windSpeed": 2.81,
              "windGust": 5.23,
              "windBearing": 220,
              "cloudCover": 0.99,
              "uvIndex": 0,
              "visibility": 16.093,
              "ozone": 345.2
          },
          {
              "time": 1573657200,
              "summary": "Overcast",
              "icon": "cloudy",
              "precipIntensity": 0.0221,
              "precipProbability": 0.04,
              "precipType": "rain",
              "temperature": 8.5,
              "apparentTemperature": 6.84,
              "dewPoint": 3.76,
              "humidity": 0.72,
              "pressure": 997.7,
              "windSpeed": 2.79,
              "windGust": 5.59,
              "windBearing": 206,
              "cloudCover": 0.99,
              "uvIndex": 0,
              "visibility": 16.093,
              "ozone": 347.2
          },
          {
              "time": 1573660800,
              "summary": "Overcast",
              "icon": "cloudy",
              "precipIntensity": 0.0227,
              "precipProbability": 0.04,
              "precipType": "rain",
              "temperature": 8.3,
              "apparentTemperature": 6.62,
              "dewPoint": 3.39,
              "humidity": 0.71,
              "pressure": 996.8,
              "windSpeed": 2.76,
              "windGust": 5.7,
              "windBearing": 184,
              "cloudCover": 0.99,
              "uvIndex": 0,
              "visibility": 16.093,
              "ozone": 350.8
          },
          {
              "time": 1573664400,
              "summary": "Overcast",
              "icon": "cloudy",
              "precipIntensity": 0.0198,
              "precipProbability": 0.05,
              "precipType": "rain",
              "temperature": 7.93,
              "apparentTemperature": 6.17,
              "dewPoint": 3.21,
              "humidity": 0.72,
              "pressure": 995.8,
              "windSpeed": 2.78,
              "windGust": 5.73,
              "windBearing": 158,
              "cloudCover": 0.99,
              "uvIndex": 0,
              "visibility": 16.093,
              "ozone": 355.3
          },
          {
              "time": 1573668000,
              "summary": "Overcast",
              "icon": "cloudy",
              "precipIntensity": 0.0203,
              "precipProbability": 0.06,
              "precipType": "rain",
              "temperature": 7.67,
              "apparentTemperature": 5.76,
              "dewPoint": 3.31,
              "humidity": 0.74,
              "pressure": 994.9,
              "windSpeed": 2.92,
              "windGust": 6.03,
              "windBearing": 137,
              "cloudCover": 0.99,
              "uvIndex": 0,
              "visibility": 16.093,
              "ozone": 358.9
          },
          {
              "time": 1573671600,
              "summary": "Overcast",
              "icon": "cloudy",
              "precipIntensity": 0.0249,
              "precipProbability": 0.11,
              "precipType": "rain",
              "temperature": 7.79,
              "apparentTemperature": 5.68,
              "dewPoint": 3.79,
              "humidity": 0.76,
              "pressure": 994,
              "windSpeed": 3.29,
              "windGust": 6.86,
              "windBearing": 130,
              "cloudCover": 0.99,
              "uvIndex": 0,
              "visibility": 16.093,
              "ozone": 360.8
          },
          {
              "time": 1573675200,
              "summary": "Overcast",
              "icon": "cloudy",
              "precipIntensity": 0.039,
              "precipProbability": 0.18,
              "precipType": "rain",
              "temperature": 8,
              "apparentTemperature": 5.66,
              "dewPoint": 4.64,
              "humidity": 0.79,
              "pressure": 993.2,
              "windSpeed": 3.78,
              "windGust": 7.97,
              "windBearing": 130,
              "cloudCover": 0.99,
              "uvIndex": 0,
              "visibility": 16.093,
              "ozone": 361.8
          },
          {
              "time": 1573678800,
              "summary": "Overcast",
              "icon": "cloudy",
              "precipIntensity": 0.0553,
              "precipProbability": 0.27,
              "precipType": "rain",
              "temperature": 8.06,
              "apparentTemperature": 5.51,
              "dewPoint": 5.11,
              "humidity": 0.82,
              "pressure": 992.5,
              "windSpeed": 4.21,
              "windGust": 8.9,
              "windBearing": 130,
              "cloudCover": 0.98,
              "uvIndex": 0,
              "visibility": 16.093,
              "ozone": 363.1
          },
          {
              "time": 1573682400,
              "summary": "Overcast",
              "icon": "cloudy",
              "precipIntensity": 0.0596,
              "precipProbability": 0.31,
              "precipType": "rain",
              "temperature": 8.01,
              "apparentTemperature": 5.32,
              "dewPoint": 5.19,
              "humidity": 0.82,
              "pressure": 991.9,
              "windSpeed": 4.48,
              "windGust": 9.44,
              "windBearing": 128,
              "cloudCover": 0.99,
              "uvIndex": 0,
              "visibility": 16.093,
              "ozone": 365.2
          },
          {
              "time": 1573686000,
              "summary": "Overcast",
              "icon": "cloudy",
              "precipIntensity": 0.0798,
              "precipProbability": 0.34,
              "precipType": "rain",
              "temperature": 8.05,
              "apparentTemperature": 5.28,
              "dewPoint": 5.17,
              "humidity": 0.82,
              "pressure": 991.2,
              "windSpeed": 4.69,
              "windGust": 9.78,
              "windBearing": 126,
              "cloudCover": 0.99,
              "uvIndex": 0,
              "visibility": 16.093,
              "ozone": 367.4
          },
          {
              "time": 1573689600,
              "summary": "Possible Drizzle",
              "icon": "rain",
              "precipIntensity": 0.1611,
              "precipProbability": 0.45,
              "precipType": "rain",
              "temperature": 8.07,
              "apparentTemperature": 5.2,
              "dewPoint": 5.07,
              "humidity": 0.81,
              "pressure": 990.7,
              "windSpeed": 4.93,
              "windGust": 10.1,
              "windBearing": 122,
              "cloudCover": 0.99,
              "uvIndex": 0,
              "visibility": 16.093,
              "ozone": 369.8
          },
          {
              "time": 1573693200,
              "summary": "Possible Light Rain",
              "icon": "rain",
              "precipIntensity": 0.4047,
              "precipProbability": 0.58,
              "precipType": "rain",
              "temperature": 8.1,
              "apparentTemperature": 5.06,
              "dewPoint": 4.99,
              "humidity": 0.81,
              "pressure": 990.3,
              "windSpeed": 5.37,
              "windGust": 10.69,
              "windBearing": 114,
              "cloudCover": 1,
              "uvIndex": 0,
              "visibility": 16.093,
              "ozone": 371.9
          },
          {
              "time": 1573696800,
              "summary": "Possible Light Rain",
              "icon": "rain",
              "precipIntensity": 0.8684,
              "precipProbability": 0.65,
              "precipType": "rain",
              "temperature": 8.09,
              "apparentTemperature": 4.87,
              "dewPoint": 4.86,
              "humidity": 0.8,
              "pressure": 990,
              "windSpeed": 5.84,
              "windGust": 11.24,
              "windBearing": 104,
              "cloudCover": 1,
              "uvIndex": 0,
              "visibility": 10.565,
              "ozone": 374
          },
          {
              "time": 1573700400,
              "summary": "Light Rain",
              "icon": "rain",
              "precipIntensity": 1.2971,
              "precipProbability": 0.7,
              "precipType": "rain",
              "temperature": 8.06,
              "apparentTemperature": 4.81,
              "dewPoint": 4.51,
              "humidity": 0.78,
              "pressure": 990,
              "windSpeed": 5.92,
              "windGust": 11,
              "windBearing": 97,
              "cloudCover": 1,
              "uvIndex": 0,
              "visibility": 7.185,
              "ozone": 376.5
          },
          {
              "time": 1573704000,
              "summary": "Light Rain",
              "icon": "rain",
              "precipIntensity": 1.4263,
              "precipProbability": 0.73,
              "precipType": "rain",
              "temperature": 7.98,
              "apparentTemperature": 4.99,
              "dewPoint": 4.19,
              "humidity": 0.77,
              "pressure": 990.4,
              "windSpeed": 5.2,
              "windGust": 9.18,
              "windBearing": 97,
              "cloudCover": 1,
              "uvIndex": 0,
              "visibility": 10.597,
              "ozone": 380.2
          },
          {
              "time": 1573707600,
              "summary": "Light Rain",
              "icon": "rain",
              "precipIntensity": 1.3763,
              "precipProbability": 0.75,
              "precipType": "rain",
              "temperature": 7.94,
              "apparentTemperature": 5.43,
              "dewPoint": 3.92,
              "humidity": 0.76,
              "pressure": 991.1,
              "windSpeed": 4.07,
              "windGust": 6.57,
              "windBearing": 101,
              "cloudCover": 1,
              "uvIndex": 0,
              "visibility": 16.093,
              "ozone": 384.2
          },
          {
              "time": 1573711200,
              "summary": "Light Rain",
              "icon": "rain",
              "precipIntensity": 1.2178,
              "precipProbability": 0.73,
              "precipType": "rain",
              "temperature": 7.8,
              "apparentTemperature": 5.71,
              "dewPoint": 3.78,
              "humidity": 0.76,
              "pressure": 991.8,
              "windSpeed": 3.26,
              "windGust": 4.77,
              "windBearing": 105,
              "cloudCover": 1,
              "uvIndex": 0,
              "visibility": 16.093,
              "ozone": 386.8
          },
          {
              "time": 1573714800,
              "summary": "Possible Light Rain",
              "icon": "rain",
              "precipIntensity": 0.9217,
              "precipProbability": 0.63,
              "precipType": "rain",
              "temperature": 7.39,
              "apparentTemperature": 5.3,
              "dewPoint": 3.63,
              "humidity": 0.77,
              "pressure": 992.6,
              "windSpeed": 3.12,
              "windGust": 4.69,
              "windBearing": 108,
              "cloudCover": 0.96,
              "uvIndex": 0,
              "visibility": 16.093,
              "ozone": 387.1
          },
          {
              "time": 1573718400,
              "summary": "Possible Light Rain",
              "icon": "rain",
              "precipIntensity": 0.679,
              "precipProbability": 0.55,
              "precipType": "rain",
              "temperature": 6.71,
              "apparentTemperature": 4.38,
              "dewPoint": 3.53,
              "humidity": 0.8,
              "pressure": 993.4,
              "windSpeed": 3.27,
              "windGust": 5.4,
              "windBearing": 112,
              "cloudCover": 0.91,
              "uvIndex": 0,
              "visibility": 16.093,
              "ozone": 386
          },
          {
              "time": 1573722000,
              "summary": "Possible Light Rain",
              "icon": "rain",
              "precipIntensity": 0.5749,
              "precipProbability": 0.48,
              "precipType": "rain",
              "temperature": 6.33,
              "apparentTemperature": 3.87,
              "dewPoint": 3.54,
              "humidity": 0.82,
              "pressure": 994.1,
              "windSpeed": 3.36,
              "windGust": 5.75,
              "windBearing": 112,
              "cloudCover": 0.84,
              "uvIndex": 0,
              "visibility": 16.093,
              "ozone": 385.4
          },
          {
              "time": 1573725600,
              "summary": "Possible Light Rain",
              "icon": "rain",
              "precipIntensity": 0.4231,
              "precipProbability": 0.4,
              "precipType": "rain",
              "temperature": 6.45,
              "apparentTemperature": 4.08,
              "dewPoint": 3.63,
              "humidity": 0.82,
              "pressure": 994.7,
              "windSpeed": 3.26,
              "windGust": 5.1,
              "windBearing": 107,
              "cloudCover": 0.73,
              "uvIndex": 0,
              "visibility": 16.093,
              "ozone": 385.9
          },
          {
              "time": 1573729200,
              "summary": "Partly Cloudy",
              "icon": "partly-cloudy-day",
              "precipIntensity": 0.2599,
              "precipProbability": 0.3,
              "precipType": "rain",
              "temperature": 7.09,
              "apparentTemperature": 4.93,
              "dewPoint": 3.91,
              "humidity": 0.8,
              "pressure": 995.2,
              "windSpeed": 3.12,
              "windGust": 4.08,
              "windBearing": 99,
              "cloudCover": 0.59,
              "uvIndex": 1,
              "visibility": 16.093,
              "ozone": 386.9
          },
          {
              "time": 1573732800,
              "summary": "Partly Cloudy",
              "icon": "partly-cloudy-day",
              "precipIntensity": 0.161,
              "precipProbability": 0.24,
              "precipType": "rain",
              "temperature": 7.78,
              "apparentTemperature": 5.8,
              "dewPoint": 4.14,
              "humidity": 0.78,
              "pressure": 995.7,
              "windSpeed": 3.07,
              "windGust": 3.45,
              "windBearing": 88,
              "cloudCover": 0.47,
              "uvIndex": 1,
              "visibility": 16.093,
              "ozone": 387.6
          },
          {
              "time": 1573736400,
              "summary": "Partly Cloudy",
              "icon": "partly-cloudy-day",
              "precipIntensity": 0.1279,
              "precipProbability": 0.23,
              "precipType": "rain",
              "temperature": 8.11,
              "apparentTemperature": 6.09,
              "dewPoint": 4.37,
              "humidity": 0.77,
              "pressure": 996.1,
              "windSpeed": 3.23,
              "windGust": 3.57,
              "windBearing": 71,
              "cloudCover": 0.35,
              "uvIndex": 1,
              "visibility": 16.093,
              "ozone": 388.1
          },
          {
              "time": 1573740000,
              "summary": "Clear",
              "icon": "clear-day",
              "precipIntensity": 0.1277,
              "precipProbability": 0.26,
              "precipType": "rain",
              "temperature": 8.04,
              "apparentTemperature": 5.88,
              "dewPoint": 4.51,
              "humidity": 0.78,
              "pressure": 996.4,
              "windSpeed": 3.47,
              "windGust": 4.08,
              "windBearing": 52,
              "cloudCover": 0.25,
              "uvIndex": 0,
              "visibility": 16.093,
              "ozone": 388.4
          },
          {
              "time": 1573743600,
              "summary": "Clear",
              "icon": "clear-day",
              "precipIntensity": 0.1279,
              "precipProbability": 0.27,
              "precipType": "rain",
              "temperature": 7.96,
              "apparentTemperature": 5.73,
              "dewPoint": 4.41,
              "humidity": 0.78,
              "pressure": 996.9,
              "windSpeed": 3.57,
              "windGust": 4.29,
              "windBearing": 42,
              "cloudCover": 0.2,
              "uvIndex": 0,
              "visibility": 16.093,
              "ozone": 387.6
          },
          {
              "time": 1573747200,
              "summary": "Clear",
              "icon": "clear-day",
              "precipIntensity": 0.0969,
              "precipProbability": 0.25,
              "precipType": "rain",
              "temperature": 7.83,
              "apparentTemperature": 5.63,
              "dewPoint": 4.47,
              "humidity": 0.79,
              "pressure": 997.7,
              "windSpeed": 3.44,
              "windGust": 3.89,
              "windBearing": 47,
              "cloudCover": 0.24,
              "uvIndex": 0,
              "visibility": 16.093,
              "ozone": 384.7
          },
          {
              "time": 1573750800,
              "summary": "Partly Cloudy",
              "icon": "partly-cloudy-night",
              "precipIntensity": 0.0655,
              "precipProbability": 0.21,
              "precipType": "rain",
              "temperature": 7.82,
              "apparentTemperature": 5.79,
              "dewPoint": 4.52,
              "humidity": 0.8,
              "pressure": 998.7,
              "windSpeed": 3.16,
              "windGust": 3.19,
              "windBearing": 54,
              "cloudCover": 0.34,
              "uvIndex": 0,
              "visibility": 16.093,
              "ozone": 380.8
          },
          {
              "time": 1573754400,
              "summary": "Partly Cloudy",
              "icon": "partly-cloudy-night",
              "precipIntensity": 0.0493,
              "precipProbability": 0.19,
              "precipType": "rain",
              "temperature": 7.69,
              "apparentTemperature": 5.83,
              "dewPoint": 4.54,
              "humidity": 0.8,
              "pressure": 999.5,
              "windSpeed": 2.86,
              "windGust": 2.86,
              "windBearing": 53,
              "cloudCover": 0.45,
              "uvIndex": 0,
              "visibility": 16.093,
              "ozone": 378
          },
          {
              "time": 1573758000,
              "summary": "Partly Cloudy",
              "icon": "partly-cloudy-night",
              "precipIntensity": 0.0442,
              "precipProbability": 0.19,
              "precipType": "rain",
              "temperature": 7.8,
              "apparentTemperature": 6.2,
              "dewPoint": 4.51,
              "humidity": 0.8,
              "pressure": 1000.5,
              "windSpeed": 2.51,
              "windGust": 2.51,
              "windBearing": 47,
              "cloudCover": 0.56,
              "uvIndex": 0,
              "visibility": 16.093,
              "ozone": 377.3
          },
          {
              "time": 1573761600,
              "summary": "Mostly Cloudy",
              "icon": "partly-cloudy-night",
              "precipIntensity": 0.0552,
              "precipProbability": 0.14,
              "precipType": "rain",
              "temperature": 7.89,
              "apparentTemperature": 6.6,
              "dewPoint": 4.52,
              "humidity": 0.79,
              "pressure": 1001.5,
              "windSpeed": 2.15,
              "windGust": 2.15,
              "windBearing": 22,
              "cloudCover": 0.69,
              "uvIndex": 0,
              "visibility": 16.093,
              "ozone": 377.6
          }
      ]
  },
  "daily": {
      "summary": "Light rain throughout the week.",
      "icon": "rain",
      "data": [
          {
              "time": 1573516800,
              "summary": "Possible light rain in the afternoon.",
              "icon": "rain",
              "sunriseTime": 1573542780,
              "sunsetTime": 1573575420,
              "moonPhase": 0.51,
              "precipIntensity": 0.0933,
              "precipIntensityMax": 0.5129,
              "precipIntensityMaxTime": 1573561680,
              "precipProbability": 0.56,
              "precipType": "rain",
              "temperatureHigh": 8.79,
              "temperatureHighTime": 1573560060,
              "temperatureLow": 6.22,
              "temperatureLowTime": 1573632000,
              "apparentTemperatureHigh": 5.59,
              "apparentTemperatureHighTime": 1573582620,
              "apparentTemperatureLow": 4.4,
              "apparentTemperatureLowTime": 1573632000,
              "dewPoint": 3.55,
              "humidity": 0.81,
              "pressure": 999.2,
              "windSpeed": 4.76,
              "windGust": 13.31,
              "windGustTime": 1573563480,
              "windBearing": 253,
              "cloudCover": 0.59,
              "uvIndex": 1,
              "uvIndexTime": 1573558860,
              "visibility": 11.331,
              "ozone": 355.5,
              "temperatureMin": 4.36,
              "temperatureMinTime": 1573544880,
              "temperatureMax": 8.79,
              "temperatureMaxTime": 1573560060,
              "apparentTemperatureMin": 1.27,
              "apparentTemperatureMinTime": 1573545120,
              "apparentTemperatureMax": 5.66,
              "apparentTemperatureMaxTime": 1573600500
          },
          {
              "time": 1573603200,
              "summary": "Light rain overnight.",
              "icon": "rain",
              "sunriseTime": 1573629300,
              "sunsetTime": 1573661700,
              "moonPhase": 0.54,
              "precipIntensity": 0.0229,
              "precipIntensityMax": 0.1611,
              "precipIntensityMaxTime": 1573689600,
              "precipProbability": 0.45,
              "precipType": "rain",
              "temperatureHigh": 8.78,
              "temperatureHighTime": 1573656540,
              "temperatureLow": 6.44,
              "temperatureLowTime": 1573718400,
              "apparentTemperatureHigh": 6.84,
              "apparentTemperatureHighTime": 1573656660,
              "apparentTemperatureLow": 4.38,
              "apparentTemperatureLowTime": 1573718400,
              "dewPoint": 4.2,
              "humidity": 0.79,
              "pressure": 998.2,
              "windSpeed": 3.29,
              "windGust": 10.1,
              "windGustTime": 1573689600,
              "windBearing": 214,
              "cloudCover": 0.71,
              "uvIndex": 1,
              "uvIndexTime": 1573645560,
              "visibility": 16.093,
              "ozone": 351.8,
              "temperatureMin": 5.98,
              "temperatureMinTime": 1573635480,
              "temperatureMax": 8.78,
              "temperatureMaxTime": 1573656540,
              "apparentTemperatureMin": 4.2,
              "apparentTemperatureMinTime": 1573635300,
              "apparentTemperatureMax": 6.84,
              "apparentTemperatureMaxTime": 1573656660
          },
          {
              "time": 1573689600,
              "summary": "Light rain in the morning and afternoon.",
              "icon": "rain",
              "sunriseTime": 1573715820,
              "sunsetTime": 1573748040,
              "moonPhase": 0.58,
              "precipIntensity": 0.4396,
              "precipIntensityMax": 1.4296,
              "precipIntensityMaxTime": 1573704600,
              "precipProbability": 0.94,
              "precipType": "rain",
              "temperatureHigh": 8.4,
              "temperatureHighTime": 1573737120,
              "temperatureLow": 5.72,
              "temperatureLowTime": 1573797660,
              "apparentTemperatureHigh": 6.2,
              "apparentTemperatureHighTime": 1573758000,
              "apparentTemperatureLow": 3.97,
              "apparentTemperatureLowTime": 1573802220,
              "dewPoint": 4.27,
              "humidity": 0.79,
              "pressure": 996,
              "windSpeed": 3.43,
              "windGust": 11.28,
              "windGustTime": 1573698060,
              "windBearing": 83,
              "cloudCover": 0.7,
              "uvIndex": 1,
              "uvIndexTime": 1573732140,
              "visibility": 15.276,
              "ozone": 382.1,
              "temperatureMin": 6.04,
              "temperatureMinTime": 1573722900,
              "temperatureMax": 8.4,
              "temperatureMaxTime": 1573737120,
              "apparentTemperatureMin": 3.85,
              "apparentTemperatureMinTime": 1573722720,
              "apparentTemperatureMax": 6.83,
              "apparentTemperatureMaxTime": 1573765560
          },
          {
              "time": 1573776000,
              "summary": "Light rain starting in the afternoon.",
              "icon": "rain",
              "sunriseTime": 1573802340,
              "sunsetTime": 1573834320,
              "moonPhase": 0.61,
              "precipIntensity": 0.1695,
              "precipIntensityMax": 0.7962,
              "precipIntensityMaxTime": 1573852440,
              "precipProbability": 0.86,
              "precipType": "rain",
              "temperatureHigh": 9.14,
              "temperatureHighTime": 1573824120,
              "temperatureLow": 6.72,
              "temperatureLowTime": 1573883880,
              "apparentTemperatureHigh": 6.12,
              "apparentTemperatureHighTime": 1573824120,
              "apparentTemperatureLow": 3.55,
              "apparentTemperatureLowTime": 1573883640,
              "dewPoint": 4.03,
              "humidity": 0.79,
              "pressure": 1006,
              "windSpeed": 4.19,
              "windGust": 15.2,
              "windGustTime": 1573850160,
              "windBearing": 358,
              "cloudCover": 0.81,
              "uvIndex": 1,
              "uvIndexTime": 1573818420,
              "visibility": 15.246,
              "ozone": 366.4,
              "temperatureMin": 5.72,
              "temperatureMinTime": 1573797660,
              "temperatureMax": 9.14,
              "temperatureMaxTime": 1573824120,
              "apparentTemperatureMin": 3.97,
              "apparentTemperatureMinTime": 1573802220,
              "apparentTemperatureMax": 6.17,
              "apparentTemperatureMaxTime": 1573776000
          },
          {
              "time": 1573862400,
              "summary": "Possible drizzle in the morning.",
              "icon": "rain",
              "sunriseTime": 1573888800,
              "sunsetTime": 1573920660,
              "moonPhase": 0.64,
              "precipIntensity": 0.0742,
              "precipIntensityMax": 0.3706,
              "precipIntensityMaxTime": 1573862400,
              "precipProbability": 0.72,
              "precipType": "rain",
              "temperatureHigh": 9.68,
              "temperatureHighTime": 1573913040,
              "temperatureLow": 5.37,
              "temperatureLowTime": 1573977480,
              "apparentTemperatureHigh": 7.47,
              "apparentTemperatureHighTime": 1573913280,
              "apparentTemperatureLow": 4.83,
              "apparentTemperatureLowTime": 1573977480,
              "dewPoint": 4.1,
              "humidity": 0.77,
              "pressure": 1006,
              "windSpeed": 4.13,
              "windGust": 10.63,
              "windGustTime": 1573884360,
              "windBearing": 347,
              "cloudCover": 0.74,
              "uvIndex": 1,
              "uvIndexTime": 1573904880,
              "visibility": 16.093,
              "ozone": 353.5,
              "temperatureMin": 6.54,
              "temperatureMinTime": 1573948800,
              "temperatureMax": 9.68,
              "temperatureMaxTime": 1573913040,
              "apparentTemperatureMin": 3.55,
              "apparentTemperatureMinTime": 1573883640,
              "apparentTemperatureMax": 7.47,
              "apparentTemperatureMaxTime": 1573913280
          },
          {
              "time": 1573948800,
              "summary": "Clear throughout the day.",
              "icon": "clear-day",
              "sunriseTime": 1573975320,
              "sunsetTime": 1574007000,
              "moonPhase": 0.68,
              "precipIntensity": 0.0043,
              "precipIntensityMax": 0.0105,
              "precipIntensityMaxTime": 1573984800,
              "precipProbability": 0.1,
              "precipType": "rain",
              "temperatureHigh": 9.85,
              "temperatureHighTime": 1573999620,
              "temperatureLow": 6.43,
              "temperatureLowTime": 1574034060,
              "apparentTemperatureHigh": 8.36,
              "apparentTemperatureHighTime": 1573999500,
              "apparentTemperatureLow": 4.59,
              "apparentTemperatureLowTime": 1574035440,
              "dewPoint": 3.03,
              "humidity": 0.75,
              "pressure": 1011,
              "windSpeed": 2.11,
              "windGust": 5.01,
              "windGustTime": 1574012520,
              "windBearing": 342,
              "cloudCover": 0.19,
              "uvIndex": 1,
              "uvIndexTime": 1573991280,
              "visibility": 16.093,
              "ozone": 317.5,
              "temperatureMin": 5.37,
              "temperatureMinTime": 1573977480,
              "temperatureMax": 9.85,
              "temperatureMaxTime": 1573999620,
              "apparentTemperatureMin": 4.6,
              "apparentTemperatureMinTime": 1574035200,
              "apparentTemperatureMax": 8.36,
              "apparentTemperatureMaxTime": 1573999500
          },
          {
              "time": 1574035200,
              "summary": "Possible drizzle in the evening and overnight.",
              "icon": "rain",
              "sunriseTime": 1574061840,
              "sunsetTime": 1574093280,
              "moonPhase": 0.71,
              "precipIntensity": 0.1366,
              "precipIntensityMax": 0.3001,
              "precipIntensityMaxTime": 1574080680,
              "precipProbability": 0.59,
              "precipType": "rain",
              "temperatureHigh": 9.91,
              "temperatureHighTime": 1574083200,
              "temperatureLow": 8.26,
              "temperatureLowTime": 1574114640,
              "apparentTemperatureHigh": 7.43,
              "apparentTemperatureHighTime": 1574084460,
              "apparentTemperatureLow": 5.68,
              "apparentTemperatureLowTime": 1574150400,
              "dewPoint": 3.89,
              "humidity": 0.74,
              "pressure": 1007.7,
              "windSpeed": 3.98,
              "windGust": 11.29,
              "windGustTime": 1574121600,
              "windBearing": 353,
              "cloudCover": 0.71,
              "uvIndex": 1,
              "uvIndexTime": 1574077740,
              "visibility": 16.093,
              "ozone": 309.1,
              "temperatureMin": 6.44,
              "temperatureMinTime": 1574035200,
              "temperatureMax": 9.91,
              "temperatureMaxTime": 1574083200,
              "apparentTemperatureMin": 4.59,
              "apparentTemperatureMinTime": 1574035440,
              "apparentTemperatureMax": 7.43,
              "apparentTemperatureMaxTime": 1574084460
          },
          {
              "time": 1574121600,
              "summary": "Possible drizzle in the morning.",
              "icon": "rain",
              "sunriseTime": 1574148300,
              "sunsetTime": 1574179620,
              "moonPhase": 0.75,
              "precipIntensity": 0.2008,
              "precipIntensityMax": 0.3994,
              "precipIntensityMaxTime": 1574132400,
              "precipProbability": 0.75,
              "precipType": "rain",
              "temperatureHigh": 10.75,
              "temperatureHighTime": 1574172180,
              "temperatureLow": 6.39,
              "temperatureLowTime": 1574224920,
              "apparentTemperatureHigh": 10.55,
              "apparentTemperatureHighTime": 1574173920,
              "apparentTemperatureLow": 4.45,
              "apparentTemperatureLowTime": 1574225640,
              "dewPoint": 4.18,
              "humidity": 0.72,
              "pressure": 1001.9,
              "windSpeed": 4.67,
              "windGust": 15.01,
              "windGustTime": 1574152800,
              "windBearing": 156,
              "cloudCover": 0.73,
              "uvIndex": 1,
              "uvIndexTime": 1574164080,
              "visibility": 15.917,
              "ozone": 304,
              "temperatureMin": 7.36,
              "temperatureMinTime": 1574208000,
              "temperatureMax": 10.75,
              "temperatureMaxTime": 1574172180,
              "apparentTemperatureMin": 5.42,
              "apparentTemperatureMinTime": 1574155680,
              "apparentTemperatureMax": 10.55,
              "apparentTemperatureMaxTime": 1574173920
          }
      ]
  },
  "flags": {
      "sources": [
          "meteoalarm",
          "cmc",
          "gfs",
          "icon",
          "isd",
          "madis",
          "darksky",
          "nearest-precip"
      ],
      "meteoalarm-license": "Based on data from EUMETNET - MeteoAlarm [https://www.meteoalarm.eu/]. Time delays between this website and the MeteoAlarm website are possible; for the most up to date information about alert levels as published by the participating National Meteorological Services please use the MeteoAlarm website.",
      "nearest-station": 5.039,
      "units": "si"
  },
  "offset": 0
};

export default weatherMock;